parameters:
            #    parameter_name: value

services:
            app.form_login_authenticator:
                class: AppBundle\Security\FormLoginAuthenticator
                arguments: ["@router", "@security.password_encoder"]
