AppBundle\Entity\UsersFriends:
    type: entity
    table: users_friends
    id:
        uidRel:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: UID_REL
            generator:
                strategy: IDENTITY
    fields:
        uid1:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: UID1
        uid2:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: UID2
        statut:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: STATUT
    lifecycleCallbacks: {  }
