AppBundle\Entity\UsersSearch:
    type: entity
    table: users_search
    id:
        uidSea:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        uid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: UID

        search:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: SEARCH
    lifecycleCallbacks: {  }
