AppBundle\Entity\UsersDevices:
    type: entity
    table: users_devices
    id:
        did:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: did
            generator:
                strategy: IDENTITY
    fields:
        uid:
            type: integer
            nullable: false
            column: uid
        brand:
            type: string
            nullable: false
            length: 30
            column: brand
        device:
            type: string
            nullable: false
            length: 30
            column: device
