AppBundle\Entity\UsersData:
    type: entity
    table: users_data
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        uid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: UID
        date:
            type: date
            nullable: true
            column: DATE
        weight:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: WEIGHT
        height:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: HEIGHT
        gender:
            type: string
            nullable: true
            length: 8
            options:
                fixed: false
            column: GENDER
        age:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: AGE
        dateOfBirth:
            type: string
            nullable: true
            length: 8
            options:
                fixed: false
            column: DATE_OF_BIRTH
        averageDailySteps:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: AVERAGEDAILYSTEPS
        strideLengthRunning:
            type: float
            nullable: true
            options:
                unsigned: false
            column: STRIDE_LENGTH_RUNNING
        strideLengthWalking:
            type: float
            nullable: true
            options:
                unsigned: false
            column: STRIDE_LENGTH_WALKING
        strideLengthRunningType:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: STRIDE_LENGTH_RUNNING_TYPE
        strideLengthWalkingType:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: STRIDE_LENGTH_WALKING_TYPE
    lifecycleCallbacks: {  }
