AppBundle\Entity\Users:
    type: entity
    table: users
    id:
        uid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: UID
            generator:
                strategy: IDENTITY
    fields:
        uname:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: UNAME
        ulastname:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: ULASTNAME
        upassword:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: UPASSWORD
        uemail:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
            column: UEMAIL
        uphone:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: UPHONE
    lifecycleCallbacks: {  }
