<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Defi extends \AppBundle\Entity\Defi implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Defi' . "\0" . 'UID', '' . "\0" . 'AppBundle\\Entity\\Defi' . "\0" . 'UNAME', '' . "\0" . 'AppBundle\\Entity\\Defi' . "\0" . 'ULASTNAME', '' . "\0" . 'AppBundle\\Entity\\Defi' . "\0" . 'UPASSWORD', '' . "\0" . 'AppBundle\\Entity\\Defi' . "\0" . 'UEMAIL', '' . "\0" . 'AppBundle\\Entity\\Defi' . "\0" . 'UPHONE', '' . "\0" . 'AppBundle\\Entity\\Defi' . "\0" . 'DID'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Defi' . "\0" . 'UID', '' . "\0" . 'AppBundle\\Entity\\Defi' . "\0" . 'UNAME', '' . "\0" . 'AppBundle\\Entity\\Defi' . "\0" . 'ULASTNAME', '' . "\0" . 'AppBundle\\Entity\\Defi' . "\0" . 'UPASSWORD', '' . "\0" . 'AppBundle\\Entity\\Defi' . "\0" . 'UEMAIL', '' . "\0" . 'AppBundle\\Entity\\Defi' . "\0" . 'UPHONE', '' . "\0" . 'AppBundle\\Entity\\Defi' . "\0" . 'DID'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Defi $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUID', []);

        return parent::getUID();
    }

    /**
     * {@inheritDoc}
     */
    public function setUNAME($uNAME)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUNAME', [$uNAME]);

        return parent::setUNAME($uNAME);
    }

    /**
     * {@inheritDoc}
     */
    public function getUNAME()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUNAME', []);

        return parent::getUNAME();
    }

    /**
     * {@inheritDoc}
     */
    public function setULASTNAME($uLASTNAME)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setULASTNAME', [$uLASTNAME]);

        return parent::setULASTNAME($uLASTNAME);
    }

    /**
     * {@inheritDoc}
     */
    public function getULASTNAME()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getULASTNAME', []);

        return parent::getULASTNAME();
    }

    /**
     * {@inheritDoc}
     */
    public function setUPASSWORD($uPASSWORD)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUPASSWORD', [$uPASSWORD]);

        return parent::setUPASSWORD($uPASSWORD);
    }

    /**
     * {@inheritDoc}
     */
    public function getUPASSWORD()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUPASSWORD', []);

        return parent::getUPASSWORD();
    }

    /**
     * {@inheritDoc}
     */
    public function setUEMAIL($uEMAIL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUEMAIL', [$uEMAIL]);

        return parent::setUEMAIL($uEMAIL);
    }

    /**
     * {@inheritDoc}
     */
    public function getUEMAIL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUEMAIL', []);

        return parent::getUEMAIL();
    }

    /**
     * {@inheritDoc}
     */
    public function setUPHONE($uPHONE)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUPHONE', [$uPHONE]);

        return parent::setUPHONE($uPHONE);
    }

    /**
     * {@inheritDoc}
     */
    public function getUPHONE()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUPHONE', []);

        return parent::getUPHONE();
    }

    /**
     * {@inheritDoc}
     */
    public function getDID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDID', []);

        return parent::getDID();
    }

}
